{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "et-receiver.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- .Values.env.config | toYaml | nindent 2}}
---
{{- end}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "et-receiver.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |-
    logging.level.root={{ .Values.et.logLevel }}

{{- if eq .Values.et.redisQueue.type "sql" }}
    spring.profiles.active={{ .Values.env.config.DB_TYPE }},msg_redis,sqli,sql_locinv,sql_metric
    redis.consumer.group=sql
{{- else if eq .Values.et.redisQueue.type "agent" }}
    spring.profiles.active={{ .Values.env.config.DB_TYPE }},msg_redis,agent_stats
    redis.consumer.group=agent
{{- else if eq .Values.et.redisQueue.type "decompile" }}
    spring.profiles.active={{ .Values.env.config.DB_TYPE }},msg_redis,decompile
    redis.consumer.group=decompile
{{- else }}
    spring.profiles.active={{ .Values.env.config.DB_TYPE }},msg_redis,hit
    redis.consumer.group=hit
{{- end }}

  application-msg_redis.properties: |-
    spring.cache.type=redis
    spring.cache.redis.enable-statistics=true
    spring.redis.host={{ .Values.et.redis.host }}
    spring.redis.port={{ .Values.et.redis.port }}
    management.health.redis.enabled=true
    redis.stream.trimCronExpression={{ .Values.et.redis.trimCronExpression }}
    redis.stream.streamLength={{ .Values.et.redis.streamLength }}

  {{- if eq .Values.env.config.DB_TYPE "postgresql" }}
  application-postgresql.properties: |-
    spring.datasource.url=jdbc:postgresql://{{ .Values.env.config.DB_URL }}/overops?useLegacyDatetimeCode=false&rewriteBatchedStatements=true
    spring.datasource.username=${DB_USER}
    spring.datasource.password=${DB_PASS}

    spring.datasource.hikari.auto-commit=false
    spring.datasource.hikari.maximumPoolSize={{ .Values.et.hikari.maximumPoolSize }}
    spring.datasource.hikari.connectionTimeout={{ .Values.et.hikari.connectionTimeout }}


    # Validate JPA Schema to ensure change sets are applied properly and are in sync with JPA Model
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.open-in-view=false

    spring.sql.init.platform=postgresql
    spring.sql.init.mode=always
  {{- end }}
